AllCops:
  NewCops: enable
  SuggestExtensions: false
  TargetRubyVersion: 3.1

inherit_gem:
  rubocop-ronin: rubocop.yml

#
# ronin-listener-dns specific exceptions
#
Layout/SpaceInsideBlockBraces:
  Exclude:
    - 'spec/server_spec.rb'
